(use gauche.net)

(define (handler sock)
  (let ((recv (socket-recv sock 1024)))
    (display "written!\n")
    (if (<= (string-length recv) 0)
      (begin
        (display "exit\n")
        (socket-close sock)
        (exit)))
    (display recv)(newline)
    (socket-send sock recv))
  (handler sock))

(define (main args)
  (display args)(newline)
  (let ((server-sock (make-server-socket `inet 5000)))
    (display "waiting...\n")
    (let ((sock (socket-accept server-sock)))
      (handler sock))))
